### ISSUE TITLE
getting extra cuts 

### ISSUE THREAD

**Issue by ShashankRama** [mingcaixiao/ColumnGenerationForCutStockProblem#1]
This is my data
**6000
[1380, 1520, 1560, 1710, 1820, 1880, 1930, 2000, 2050, 2100, 2140, 2150, 2200]
[22, 25, 12, 14, 18, 18, 20, 10, 12, 14, 16, 18, 20]**

**_Total parts are 219. But in the result_**
pattern_0:	2000x3 	1
pattern_1:	1380x1 	1520x3 			6
pattern_2:	1380x2 	1560x2 			2
pattern_3:	1710x1 	2140x1 	2150x1 	11
pattern_4:	1380x3 	1820x1 			3
pattern_5:	1930x2 	2100x1 			5
pattern_6:	1880x2 	2200x1 			9
pattern_7:	1820x1 	2050x1 	2100x1 	9
pattern_8:	1930x2 	2140x1 			5
pattern_9:	1820x1 	2000x1 	2150x1 	7
pattern_10:	1710x1 	2050x1 	2200x1 	3
pattern_11:	1560x1 	2200x2 			4
pattern_12:	1380x1 	1520x2 	1560x1 	4

we are getting **222** parts 
**1380, 1520 & 1820 has one extra cut.**

**Comment by mingcaixiao** [comment]
In Final problem Model,I Use "**Great or Equal**" constraint.For Instance,In [CPP project ](https://github.com/mingcaixiao/ColumnGenerationForCutStockProblem/blob/95f570bceaa72a1f0ae96d8634ec003c27a47a3f/cpp/src/main.cpp#LL160C83-L160C83 ) 
`MPConstraint* const c = solver->MakeRowConstraint(data.demand.at(i), infinity)`   
There has two method to make parts num equal demand

1. You can change demand constraint from Great or Equal (>=) to Eqaul (==),So code above should writed as `MPConstraint* const c = solver->MakeRowConstraint(data.demand.at(i), data.demand.at(i)) `       
2. You can do a post-process to remove extra parts.In this case, after removing extra parts,some patterns will can combine to less patterns.You can use other methods to process combination such as First Fit Decreasing Algorithm.
